# Generated by Django 2.2 on 2019-04-16 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlist',
            name='smile',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherlist',
            name='today',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
