# Generated by Django 2.2 on 2019-04-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190417_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlist',
            name='smile',
            field=models.BooleanField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='1', max_length=2),
        ),
    ]
